version: '3'

services:
  springboot:
    image: "springboot-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
    volumes:
      - .:/usr/src/reprova
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: