package br.ufmg.reuso.marcelosg.reprova.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.util.Map;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Question {

    /**
     * The id of the question.
     * When null, the id will be automatically generated by the database.
     */
    @Id
    @GeneratedValue
    private Integer id;
    /**
     * The theme of the question. Mustn't be null nor empty.
     */
    private String theme;
    /**
     * The description of the question. Mustn't be null nor empty.
     */
    private String description;
    /**
     * The statement of the question. May be null or empty.
     */
    private String statement;
    /**
     * The record of the question per semester per class. Mustn't be null, may be empty.
     */
    // TODO No records in this initial implementation
//    private Map<Semester, Map<String, Float>> record;
    /**
     * Whether the question is private.
     */
    private Boolean pvt;
}
